stages:
  - build

default:
  image: node:latest
  cache: &global_cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - node_modules/
    policy: pull
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install

build-package:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
