stages:
  - restore
  - static-typing
  - lint
  - build
  - test
  - publish

default:
  image: node:latest
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install

restore-job:
  stage: restore
  script:
    - pnpm install

static-typing-job:
  stage: static-typing
  script:
    - pnpm type-check

lint-job:
  stage: lint
  script:
    - pnpm lint

build-job:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/

test-job:
  stage: test
  script:
    - pnpm test